
import { Event } from '@/types/database.types';

// Helper function to get future dates
const getFutureDate = (daysFromNow: number, hour: number = 12, minute: number = 0): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
};

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    title: 'Afro-Caribbean Brunch & Day Party',
    subtitle: 'Vibes, Food & Culture',
    description: 'Join us for an unforgettable afternoon celebrating Afro-Caribbean culture with authentic cuisine, live music, and great vibes. Featuring dishes from Jamaica, Trinidad, Haiti, and more. DJ spinning the best Afrobeats, Soca, and Dancehall all day long.',
    event_type: 'Brunch',
    diaspora_focus: ['Caribbean', 'African'],
    cuisines_highlighted: ['Jamaican', 'Trinidadian', 'Haitian'],
    city: 'Miami',
    state: 'FL',
    venue_name: 'Wynwood Warehouse',
    venue_address_line1: '2550 NW 2nd Ave',
    venue_zip: '33127',
    latitude: 25.8005,
    longitude: -80.1995,
    start_datetime: getFutureDate(7, 12, 0),
    end_datetime: getFutureDate(7, 18, 0),
    is_all_day: false,
    is_online: false,
    linked_vendor_id: '2',
    hero_image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    capacity: 200,
    ticket_required: true,
    ticket_url: 'https://eventbrite.com/example',
    is_featured: true,
    is_published: true,
    created_by_admin_id: 'admin1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Nigerian Food Festival',
    subtitle: 'Taste of Lagos',
    description: 'Experience the rich flavors of Nigeria at our annual food festival. Sample jollof rice, suya, puff puff, and more from the best Nigerian chefs in the city. Live performances, cooking demonstrations, and cultural exhibits.',
    event_type: 'Festival',
    diaspora_focus: ['African'],
    cuisines_highlighted: ['Nigerian'],
    city: 'Houston',
    state: 'TX',
    venue_name: 'Discovery Green',
    venue_address_line1: '1500 McKinney St',
    venue_zip: '77010',
    latitude: 29.7536,
    longitude: -95.3594,
    start_datetime: getFutureDate(14, 11, 0),
    end_datetime: getFutureDate(14, 20, 0),
    is_all_day: false,
    is_online: false,
    hero_image: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800',
    capacity: 500,
    ticket_required: false,
    is_featured: true,
    is_published: true,
    created_by_admin_id: 'admin1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Soul Food Sunday Supper Club',
    subtitle: 'Classic Comfort, Modern Twist',
    description: 'An intimate dining experience featuring elevated soul food classics. Chef Marcus presents a 5-course tasting menu with wine pairings. Limited seating available. Dress code: Smart casual.',
    event_type: 'Tasting',
    diaspora_focus: ['African American'],
    cuisines_highlighted: ['Soul Food', 'Southern'],
    city: 'Atlanta',
    state: 'GA',
    venue_name: 'Soul Food Kitchen',
    venue_address_line1: '789 Peachtree St',
    venue_zip: '30303',
    latitude: 33.7490,
    longitude: -84.3880,
    start_datetime: getFutureDate(21, 18, 0),
    end_datetime: getFutureDate(21, 22, 0),
    is_all_day: false,
    is_online: false,
    linked_vendor_id: '3',
    hero_image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800',
    capacity: 40,
    ticket_required: true,
    ticket_url: 'https://resy.com/example',
    is_featured: false,
    is_published: true,
    created_by_admin_id: 'admin1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Ethiopian Coffee Ceremony & Tasting',
    subtitle: 'Traditional Coffee Experience',
    description: 'Learn about the ancient Ethiopian coffee ceremony and taste some of the finest Ethiopian coffee beans. Our coffee master will guide you through the traditional preparation process and explain the cultural significance.',
    event_type: 'Tasting',
    diaspora_focus: ['African'],
    cuisines_highlighted: ['Ethiopian'],
    city: 'New York City',
    state: 'NY',
    venue_name: 'Addis Ethiopian Restaurant',
    venue_address_line1: '654 Broadway',
    venue_zip: '10012',
    latitude: 40.7128,
    longitude: -74.0060,
    start_datetime: getFutureDate(5, 15, 0),
    end_datetime: getFutureDate(5, 17, 0),
    is_all_day: false,
    is_online: false,
    linked_vendor_id: '5',
    hero_image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
    capacity: 25,
    ticket_required: true,
    ticket_url: 'https://eventbrite.com/example',
    is_featured: false,
    is_published: true,
    created_by_admin_id: 'admin1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Pan-African Food Market',
    subtitle: 'Celebrating Diaspora Flavors',
    description: 'A vibrant marketplace featuring food vendors, artisans, and performers from across the African diaspora. Shop for authentic ingredients, enjoy live cooking demos, and connect with your community.',
    event_type: 'Market',
    diaspora_focus: ['African American', 'Caribbean', 'African', 'Pan-African'],
    cuisines_highlighted: ['Nigerian', 'Jamaican', 'Soul Food', 'Ethiopian', 'Ghanaian'],
    city: 'Los Angeles',
    state: 'CA',
    venue_name: 'Grand Park',
    venue_address_line1: '200 N Grand Ave',
    venue_zip: '90012',
    latitude: 34.0555,
    longitude: -118.2467,
    start_datetime: getFutureDate(28, 10, 0),
    end_datetime: getFutureDate(28, 18, 0),
    is_all_day: false,
    is_online: false,
    hero_image: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800',
    capacity: 1000,
    ticket_required: false,
    is_featured: true,
    is_published: true,
    created_by_admin_id: 'admin1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Jerk Chicken Cook-Off',
    subtitle: 'Battle of the Best',
    description: 'Watch as the top Caribbean chefs compete for the title of Best Jerk Chicken in the city. Taste samples from each competitor and vote for your favorite. Live reggae music and Caribbean vibes all day.',
    event_type: 'Party',
    diaspora_focus: ['Caribbean'],
    cuisines_highlighted: ['Jamaican', 'Caribbean'],
    city: 'Miami',
    state: 'FL',
    venue_name: 'Bayfront Park',
    venue_address_line1: '301 Biscayne Blvd',
    venue_zip: '33132',
    latitude: 25.7743,
    longitude: -80.1862,
    start_datetime: getFutureDate(35, 12, 0),
    end_datetime: getFutureDate(35, 19, 0),
    is_all_day: false,
    is_online: false,
    hero_image: 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=800',
    capacity: 300,
    ticket_required: true,
    ticket_url: 'https://eventbrite.com/example',
    is_featured: false,
    is_published: true,
    created_by_admin_id: 'admin1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
