
import { MenuItem, MenuCategory } from '@/types/database.types';

export const MOCK_MENU_CATEGORIES: MenuCategory[] = [
  {
    id: 'cat1',
    vendor_id: '1',
    name: 'Jollof & Mains',
    sort_order: 1,
  },
  {
    id: 'cat2',
    vendor_id: '1',
    name: 'Soups & Stews',
    sort_order: 2,
  },
  {
    id: 'cat3',
    vendor_id: '1',
    name: 'Sides & Snacks',
    sort_order: 3,
  },
  {
    id: 'cat4',
    vendor_id: '2',
    name: 'Jerk Specialties',
    sort_order: 1,
  },
  {
    id: 'cat5',
    vendor_id: '2',
    name: 'Curry Dishes',
    sort_order: 2,
  },
];

export const MOCK_MENU_ITEMS: MenuItem[] = [
  {
    id: 'item1',
    vendor_id: '1',
    category_id: 'cat1',
    name: 'Jollof Rice with Chicken',
    description: 'Our signature jollof rice cooked with tomatoes, peppers, and spices, served with grilled chicken.',
    diaspora_segment_tag: 'African',
    cuisine_tag: 'Nigerian',
    price: 16.99,
    is_available: true,
    is_highlighted: true,
    item_image: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400',
    spicy_level: 'Medium',
    is_vegetarian: false,
    is_vegan: false,
    is_gluten_free: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item2',
    vendor_id: '1',
    category_id: 'cat1',
    name: 'Fried Rice',
    description: 'Nigerian-style fried rice with mixed vegetables, shrimp, and chicken.',
    diaspora_segment_tag: 'African',
    cuisine_tag: 'Nigerian',
    price: 15.99,
    is_available: true,
    is_highlighted: false,
    item_image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
    spicy_level: 'Mild',
    is_vegetarian: false,
    is_vegan: false,
    is_gluten_free: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item3',
    vendor_id: '1',
    category_id: 'cat2',
    name: 'Egusi Soup',
    description: 'Traditional melon seed soup with spinach, meat, and fish. Served with pounded yam or fufu.',
    diaspora_segment_tag: 'African',
    cuisine_tag: 'Nigerian',
    price: 18.99,
    is_available: true,
    is_highlighted: true,
    item_image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
    spicy_level: 'Hot',
    is_vegetarian: false,
    is_vegan: false,
    is_gluten_free: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item4',
    vendor_id: '1',
    category_id: 'cat3',
    name: 'Puff Puff',
    description: 'Sweet fried dough balls, a popular Nigerian snack.',
    diaspora_segment_tag: 'African',
    cuisine_tag: 'Nigerian',
    price: 5.99,
    is_available: true,
    is_highlighted: false,
    item_image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400',
    spicy_level: 'None',
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item5',
    vendor_id: '2',
    category_id: 'cat4',
    name: 'Jerk Chicken',
    description: 'Authentic Jamaican jerk chicken marinated in our secret spice blend and grilled to perfection.',
    diaspora_segment_tag: 'Caribbean',
    cuisine_tag: 'Jamaican',
    price: 14.99,
    is_available: true,
    is_highlighted: true,
    item_image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400',
    spicy_level: 'Hot',
    is_vegetarian: false,
    is_vegan: false,
    is_gluten_free: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'item6',
    vendor_id: '2',
    category_id: 'cat5',
    name: 'Curry Goat',
    description: 'Tender goat meat slow-cooked in aromatic Caribbean curry sauce.',
    diaspora_segment_tag: 'Caribbean',
    cuisine_tag: 'Jamaican',
    price: 17.99,
    is_available: true,
    is_highlighted: true,
    item_image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    spicy_level: 'Medium',
    is_vegetarian: false,
    is_vegan: false,
    is_gluten_free: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
