
import { Vendor } from '@/types/database.types';

export const MOCK_VENDORS: Vendor[] = [
  {
    id: '1',
    owner_user_id: '1',
    vendor_type: 'restaurant',
    name: 'Mama Oliseh\'s Kitchen',
    tagline: 'Authentic Nigerian Cuisine',
    description: 'Experience the rich flavors of Nigeria with our traditional dishes made from family recipes passed down through generations.',
    diaspora_focus: ['African'],
    cuisines: ['Nigerian'],
    phone: '(555) 123-4567',
    email: 'info@mamaoliseh.com',
    address_line1: '123 Main Street',
    city: 'Los Angeles',
    state: 'CA',
    zip_code: '90001',
    country: 'USA',
    latitude: 34.0522,
    longitude: -118.2437,
    is_active: true,
    onboarding_status: 'active',
    created_by_admin: false,
    logo_image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400',
    cover_image: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800',
    offers_dine_in: true,
    offers_pickup: true,
    offers_delivery: true,
    delivery_partners: ['In-house', 'UberEats', 'DoorDash'],
    min_order_amount: 15,
    avg_price_level: '$$',
    rating_average: 4.8,
    rating_count: 234,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    owner_user_id: '2',
    vendor_type: 'restaurant',
    name: 'Island Spice',
    tagline: 'Caribbean Flavors & Vibes',
    description: 'Bringing the taste of the Caribbean to your table with jerk chicken, curry goat, and more island favorites.',
    diaspora_focus: ['Caribbean'],
    cuisines: ['Jamaican', 'Caribbean'],
    phone: '(555) 234-5678',
    email: 'hello@islandspice.com',
    address_line1: '456 Ocean Ave',
    city: 'Miami',
    state: 'FL',
    zip_code: '33101',
    country: 'USA',
    latitude: 25.7617,
    longitude: -80.1918,
    is_active: true,
    onboarding_status: 'active',
    created_by_admin: false,
    logo_image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
    cover_image: 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=800',
    offers_dine_in: true,
    offers_pickup: true,
    offers_delivery: true,
    delivery_partners: ['In-house', 'Grubhub'],
    min_order_amount: 20,
    avg_price_level: '$$',
    rating_average: 4.6,
    rating_count: 189,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    owner_user_id: '3',
    vendor_type: 'restaurant',
    name: 'Soul Food Kitchen',
    tagline: 'Southern Comfort Food',
    description: 'Classic soul food made with love. Fried chicken, mac & cheese, collard greens, and all your favorites.',
    diaspora_focus: ['African American'],
    cuisines: ['Soul Food', 'Southern'],
    phone: '(555) 345-6789',
    email: 'contact@soulfoodkitchen.com',
    address_line1: '789 Peachtree St',
    city: 'Atlanta',
    state: 'GA',
    zip_code: '30303',
    country: 'USA',
    latitude: 33.7490,
    longitude: -84.3880,
    is_active: true,
    onboarding_status: 'active',
    created_by_admin: false,
    logo_image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=400',
    cover_image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800',
    offers_dine_in: true,
    offers_pickup: true,
    offers_delivery: true,
    delivery_partners: ['DoorDash', 'UberEats'],
    min_order_amount: 12,
    avg_price_level: '$',
    rating_average: 4.9,
    rating_count: 412,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    owner_user_id: '4',
    vendor_type: 'grocery',
    name: 'Afro Market',
    tagline: 'Your African Grocery Store',
    description: 'Find all your favorite African ingredients, spices, and products in one place.',
    diaspora_focus: ['African'],
    cuisines: ['Nigerian', 'Ghanaian', 'Ethiopian'],
    phone: '(555) 456-7890',
    email: 'info@afromarket.com',
    address_line1: '321 Market Street',
    city: 'Houston',
    state: 'TX',
    zip_code: '77002',
    country: 'USA',
    latitude: 29.7604,
    longitude: -95.3698,
    is_active: true,
    onboarding_status: 'active',
    created_by_admin: false,
    logo_image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400',
    cover_image: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=800',
    offers_dine_in: false,
    offers_pickup: true,
    offers_delivery: true,
    delivery_partners: ['In-house'],
    min_order_amount: 25,
    avg_price_level: '$$',
    rating_average: 4.7,
    rating_count: 156,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    owner_user_id: '5',
    vendor_type: 'restaurant',
    name: 'Addis Ethiopian Restaurant',
    tagline: 'Traditional Ethiopian Dining',
    description: 'Enjoy authentic Ethiopian cuisine served on injera with traditional coffee ceremonies.',
    diaspora_focus: ['African'],
    cuisines: ['Ethiopian'],
    phone: '(555) 567-8901',
    email: 'info@addisrestaurant.com',
    address_line1: '654 Broadway',
    city: 'New York City',
    state: 'NY',
    zip_code: '10012',
    country: 'USA',
    latitude: 40.7128,
    longitude: -74.0060,
    is_active: true,
    onboarding_status: 'active',
    created_by_admin: false,
    logo_image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400',
    cover_image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    offers_dine_in: true,
    offers_pickup: true,
    offers_delivery: false,
    delivery_partners: [],
    min_order_amount: 0,
    avg_price_level: '$$',
    rating_average: 4.8,
    rating_count: 298,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
